import type { Metadata } from "next";
import localFont from "next/font/local";
import "../src/assets/styles/main.scss";
import HeaderProps from "./headerProps";

const RobotoFlex = localFont({
    src: "/fonts/RobotoFlex.woff2",
    variable: "--RobotoFlex",
    weight: "100 900",
});

const Montserrat = localFont({
    src: "./fonts/Montserrat.woff2",
    variable: "--montserrat",
    weight: "100 900",
});

const Nunito = localFont({
    src: "./fonts/Nunito.woff2",
    variable: "--nunito",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr-FR">
            <body
                className={`${RobotoFlex.variable} ${Montserrat.variable} ${Nunito.variable}`}
                id="scroll-start"
            >
                <HeaderProps />
                <main>{children}</main>
            </body>
        </html>
    );
}
